env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
      CFLAGS=-m32
      CPPFLAGS=-m32
      CXXFLAGS=-m32
      LDFLAGS=-m32
      HOSTBUILD="--host=i686-pc-linux-gnu --build=x86_64-pc-linux-gnu"
  global:
    - ZMQ_VERSION=4.1.5
language: cpp
sudo: required
dist: trusty
matrix:
  fast_finish: true
before_install:
 - sudo apt-get update -y
 - sudo apt-get install libpgm-dev gcc-multilib g++-multilib -y
install:
 - git clone -b stable --depth 1 --quiet git://github.com/jedisct1/libsodium.git
 - git clone --depth 1 --quiet https://github.com/zeromq/jzmq.git
 - wget https://github.com/zeromq/zeromq4-1/releases/download/v4.1.5/zeromq-${ZMQ_VERSION}.tar.gz
 - tar xzvf zeromq-${ZMQ_VERSION}.tar.gz
script:
 - export CPPFLAGS="$CPPFLAGS -I${HOME}/${ARCH}/include"
 - export LDFLAGS="$LDFLAGS -L${HOME}/${ARCH}/lib"
 - cd libsodium
 - ./autogen.sh
 - ./configure --prefix=${HOME}/${ARCH} $HOSTBUILD
 - make install
 - cd ..
 - cd zeromq-${ZMQ_VERSION}
 - ./autogen.sh
 - LDFLAGS="$LDFLAGS -lsodium" sodium_CFLAGS=${HOME}/${ARCH}/include sodium_LIBS=${HOME}/${ARCH}/libs ./configure --with-libsodium --prefix=${HOME}/${ARCH} $HOSTBUILD
 - make V=1 install
 - cd ..
 - cd jzmq/jzmq-jni
 - ./autogen.sh
 - ./configure --prefix=${HOME}/${ARCH} $HOSTBUILD
 - make install
 - cd
 - cd ${HOME}/${ARCH}/lib
 - zip ${HOME}/zeromq-native.zip libjzmq.so libzmq.so libsodium.so
 - cd
addons:
  artifacts:
    debug: true
    paths:
     - zeromq-native.zip
    target_paths: ${ZMQ_VERSION}/${ARCH}
    permissions: public-read
