version: build-{build}

clone_depth: 1

skip_tags: true

os: Visual Studio 2015

environment:
  CMAKE_GENERATOR: "Visual Studio 14 2015"
  MSVCVERSION: "v140"
  MSVCYEAR: "vs2015"
  ZMQ_VERSION: "4.1.5"
  matrix:
    - platform: Win32
      configuration: Release
    - platform: x64
      configuration: Release

matrix:
  fast_finish: false

init:
  - cmake --version
  - msbuild /version
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: if "%Platform%"=="x64" set "CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64"
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: set LIBSODIUMDIR=C:\projects\libsodium
  - cmd: git clone --branch stable --depth 1 --quiet "https://github.com/jedisct1/libsodium.git" %LIBSODIUMDIR%
  - cmd: msbuild /v:minimal /maxcpucount:%NUMBER_OF_PROCESSORS% /p:Configuration=%Configuration%DLL %LIBSODIUMDIR%\builds\msvc\%MSVCYEAR%\libsodium\libsodium.vcxproj
  - cmd: set SODIUM_LIBRARY_DIR="%LIBSODIUMDIR%\bin\%Platform%\%Configuration%\%MSVCVERSION%\dynamic"
  - cmd: set SODIUM_INCLUDE_DIR="%LIBSODIUMDIR%\src\libsodium\include"
  - cmd: move "%SODIUM_LIBRARY_DIR%\libsodium.lib" "%SODIUM_LIBRARY_DIR%\sodium.lib"

before_build:
  - cmd: cd c:\projects
  - cmd: set LIBZMQ_BUILDDIR=C:\projects\libzmq
  - cmd: md "%LIBZMQ_BUILDDIR%"
  - cmd: git clone --depth 1 --quiet "https://github.com/zeromq/libzmq.git" %LIBZMQ_BUILDDIR%-src
  - cd "%LIBZMQ_BUILDDIR%"
  - cmd: cmake -D CMAKE_INCLUDE_PATH="%SODIUM_INCLUDE_DIR%" -D CMAKE_LIBRARY_PATH="%SODIUM_LIBRARY_DIR%" -D CMAKE_C_FLAGS_RELEASE="/MT" -D CMAKE_C_FLAGS_DEBUG="/MTd" -G "%CMAKE_GENERATOR%" %LIBZMQ_BUILDDIR%-src
build:
  parallel: true
  project: C:\projects\libzmq\ZeroMQ.sln
  verbosity: minimal

after_build:
  - cmd: copy "%LIBZMQ_BUILDDIR%/bin/%Configuration%/libzmq*.dll" "%LIBZMQ_BUILDDIR%/lib/%Configuration%/libzmq.dll"
  - cmd: set LIBJZMQDIR=C:/projects/jzmq
  - cmd: git clone --depth 1 --quiet https://github.com/lukepalmer/jzmq.git %LIBJZMQDIR%-src
  - cmd: md "%LIBJZMQDIR%"
  - cmd: cd "%LIBJZMQDIR%"
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DLIBZMQ_INCLUDE_DIR="%LIBZMQ_BUILDDIR%-src/include" -DLIBZMQ_LINK_DIR="%LIBZMQ_BUILDDIR%/bin/%Configuration%" "%LIBJZMQDIR%-src/jzmq-jni"
  - cmd: msbuild /v:minimal /maxcpucount:%NUMBER_OF_PROCESSORS% /p:Configuration=%Configuration% %LIBJZMQDIR%/JZMQ.sln
  - cmd: cd "%LIBZMQ_BUILDDIR%/bin/%Configuration%"
  - cmd: copy "%SODIUM_LIBRARY_DIR%/libsodium.dll" .
  - cmd: 7z a -y -bd -mx=9 libzmq.zip libzmq.dll libsodium.dll
  - ps: Push-AppveyorArtifact "libzmq.zip" -Filename "zeromq-native-${env:Platform}-${env:Configuration}-${env:ZMQ_VERSION}.zip"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
